version: '2.1'

services:
  jupyterlab:
    image: silaskalmbach/jupyterlab:latest
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - jupytercache:/home/workdir
    environment:
      SERVICE_NAME: jupyterlab
      TZ: Europe/Berlin
      TOKEN: secure_token
      PASSWORD: secure_psw
      PORT: 8888
    ports:
      - 80:8888
    
volumes:
  jupytercache: